updating code owners
pm4ml/mojaloop-payment-manager-helm pull request #115
Opened 2022-02-10 12:59 UTC by dfry

2022-02-10 13:01 UTC, mdebarros approved these changes
+1

2022-02-10 13:16 UTC, kirgene requested changes

2022-02-10 13:16 UTC, kirgene commented on CODEOWNERS
> +*    david.fry@modusbox.com juan.correa@modusbox.com yevhen.kyriukha@modusbox.com miguel.debarros@modusbox.com
Please split each user per line

2022-02-11 10:36 UTC, kirgene approved these changes

2022-02-11 10:46 UTC, dfry commented
@mdebarros please approve

2022-03-16 14:06 UTC, mdebarros approved these changes
+1

2022-03-16 14:07 UTC, merged